version: '3'

services:
  db:
    image: postgres:14.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: medtrack
    container_name: db-medtrack
    volumes:
      - ./postgres:/var/lib/postgresql/data